# Generated by Django 4.2.13 on 2026-06-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True, unique=True)),
                ('carrier', models.CharField(choices=[('GHTK', 'Giao Hàng Tiết Kiệm'), ('GHN', 'Giao Hàng Nhanh'), ('VNPOST', 'VNPost'), ('VIETTEL', 'Viettel Post')], default='GHN', max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ lấy hàng'), ('PICKED_UP', 'Đã lấy hàng'), ('IN_TRANSIT', 'Đang vận chuyển'), ('OUT_FOR_DELIVERY', 'Đang giao'), ('DELIVERED', 'Đã giao'), ('FAILED', 'Giao thất bại')], default='PENDING', max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_address', models.TextField(blank=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='ShipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.shipment')),
            ],
            options={
                'db_table': 'shipment_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
