# Generated by Django 4.2.13 on 2026-06-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.CharField(choices=[('book', 'Sách'), ('phone', 'Điện thoại'), ('laptop', 'Laptop'), ('tablet', 'Máy tính bảng'), ('fashion', 'Thời trang'), ('appliance', 'Gia dụng'), ('cosmetics', 'Mỹ phẩm'), ('food', 'Thực phẩm'), ('toy', 'Đồ chơi'), ('sport', 'Thể thao')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class hoặc emoji', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Thuộc tính đặc thù theo category (JSON)')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(db_column='category_slug', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='app.category')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_categor_0eb32c_idx'), models.Index(fields=['name'], name='products_name_6f9890_idx')],
            },
        ),
    ]
