# Generated by Django 4.2.13 on 2026-06-12 01:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('VNPAY', 'VNPay'), ('MOMO', 'MoMo'), ('STRIPE', 'Stripe')], default='COD', max_length=20)),
                ('status', models.CharField(choices=[('PROCESSING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PROCESSING', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['order_id'], name='payments_order_i_b32b33_idx')],
            },
        ),
    ]
